url: https://lubieniebieski.pl
baseurl: ""
title: Blue Corner by Adam Nowak
description: >
  #proudfather #team #leader #0092ca #focused #fullofempathy
  #photos #remote #developer #coding #coffee #travel"
twitter_username: lubieniebieski
github_username:  lubieniebieski
instagram_username:  lubieniebieski

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

google_analytics: UA-113111193-1
disqus:
  shortname: lubieniebieski
permalink: /blog/:year-:month/:title
author: Adam Nowak
show_excerpts: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
      author: "Adam Nowak"
