name: lubieniebieski blog
url: lubieniebieski.github.io
description: mostly dev-related blog written buy a guy which loves blue color
author:
  name: adam nowak
  about: ruby on rails dev @ netguru
  twitter: lubieniebieski
  github: lubieniebieski
markdown: redcarpet
pygments: true
