title: Blue Corner by Adam Nowak
description: >
  #proudfather #team #leader #0092ca #focused #fullofempathy #travel"
  #photos #remote #developer #coding #ruby #rails #drinkingcoffee #cats"
twitter_username: lubieniebieski
github_username:  lubieniebieski

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji
google_analytics: UA-113111193-1
permalink: /blog/:year-:month/:title
author: Adam Nowak
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
      author: "Adam Nowak"
