name: Makefile CI

on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint all files
        run: make
